DW: false
batch_size: 64
beta: 0.0
config: configs/cifar100_vit.yaml
dataroot: data
dataset: CIFAR100
debug_mode: 0
eps: 0.0
first_split_size: 10
gpuid:
- 0
- 1
- 2
- 3
learner_name: NormalNN
learner_type: default
log_dir: _outputs/sep_1/CIFAR100/10-task/vit/base
lr: 0.0001
max_task: -1
memory: 0
model_name: vit_pt_imnet
model_type: resnet
momentum: 0.9
mu: 0.0
optimizer: Adam
oracle_flag: false
other_split_size: 10
overwrite: 0
rand_split: true
repeat: 1
schedule:
- 5
schedule_type: decay
temp: 2.0
train_aug: true
upper_bound_flag: false
validation: false
vis_flag: false
weight_decay: 0
workers: 8
