dataset: DomainNet
first_split_size: 69
other_split_size: 69
schedule:
- 20
schedule_type: decay
batch_size: 64
optimizer: Adam
lr: 0.0001
momentum: 0.9
weight_decay: 0
model_type: zoo
model_name: vit_pt_imnet
vis_flag: False
max_task: -1
dataroot: data
workers: 8
validation: False
train_aug: True
rand_split: True
