dataset: ImageNet_R
first_split_size: 10
other_split_size: 10
schedule:
- 30
schedule_type: cosine
batch_size: 64
optimizer: Adam
lr: 0.003
momentum: 0.9
weight_decay: 0
model_type: zoo_clip
model_name: clip_pt
vis_flag: False
max_task: 5
dataroot: data
workers: 8
validation: False
train_aug: True
rand_split: True
freeze_encoder: True