dataset: ImageNet_R
first_split_size: 120
other_split_size: 120
start_class: 0
end_class: 120
schedule:
- 20
schedule_type: cosine
batch_size: 64
optimizer: Adam
lr: 0.005
momentum: 0.9
weight_decay: 0
model_type: zoo_old
model_name: vit_pt_imnet
vis_flag: False
max_task: 1
dataroot: data
workers: 8
validation: False
train_aug: True
rand_split: True
freeze_encoder: False