dataset: ImageNet_R
first_split_size: 10
other_split_size: 10
schedule:
- 40
schedule_type: cosine
batch_size: 32
optimizer: Adam
lr: 0.005
momentum: 0.9
weight_decay: 0
model_type: zoo_old
model_name: vit_pt_imnet
vis_flag: False
max_task: 20
dataroot: data
workers: 8
validation: False
train_aug: True
rand_split: True
freeze_encoder: False